version: "3.9"

services:
  minio: # S3 compatible
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    env_file: ./.env

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=apidb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  postgres_data: