version: "3.9"

services:
  minio: # S3 compatible
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - .docker/minio:/data
    command: server --console-address ":9001" /data
    env_file: ./.env

  db:
    image: postgres:16
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - .docker/postgres:/data/postgres